# Generated by Django 3.2.16 on 2022-11-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1932-02-25'),
            preserve_default=False,
        ),
    ]
